### ISSUE TITLE
world should update from bottom to top

### ISSUE THREAD

**Issue by GuuJiang** [hola/challenge_jsdash#4]
when more loose objects stack together vertically, they fall abnormally, which can be avoid by iterating objects bottom first when updating.

**Comment by feldgendler** [comment]
This logic is copied from the original 1984 game. They update top-to-bottom, and they, too, sometimes exhibit weird falling behavior.

**Comment by GuuJiang** [comment]
This is not only about behavior, indeed, this logic brought uncertainty, considering the following example.
```
##############
#  1         #
#  2         #
#  3         #
#            #
#   4        #
#            #
#            #
#     A      #
##############
```
1,2,3,4 are all boulders, the numbers are for clarification, next frame, it become
```
##############
#  1         #
#  2         #
#  3         #
#            #
#   4        #
#            #
#            #
#     A      #
##############
```
then
```
##############
#  1         #
#  2         #
#            #
#  3         #
#            #
#   4        #
#            #
#     A      #
##############
```
1 and 2 do not roll since 2 and 3 are moving and not treated as round, however, if scene 2 is the original state, it will become a different state
```
##############
# 1          #
# 2          #
#            #
#  3         #
#            #
#   4        #
#            #
#     A      #
##############
```
see? one identical scene leading to different results depending on the previous state, this will not be a problem to the main game engine since it maintain the whole history of states, but the situation is different to AI, according to the protocol, AI receive each intermediate state independently, and should work properly even missed some frame, so it is necessary to meet the basic principle that each screen should identify subsequent transitions.

this problem does not exist when update bottom to top, i think this issue still need to reopen and fix.

**Comment by feldgendler** [comment]
Yes, this is also how the original game behaves. Boulders have a hidden state: they are either “stationary” or “falling”, and it's not directly visible from a single screenshot. The goal is to learn to play the game as it is, without tweaking it to make it more suitable for AI.

> according to the protocol, AI receive each intermediate state independently

This is not true. The AI can be as stateful as you want. Nothing prevents your generator from keeping internal state.
