### ISSUE TITLE
Counter clockwise butterfly movement path

### ISSUE THREAD

**Issue by proprogrammer2015** [hola/challenge_jsdash#8]
Is that correct, that counter clockwise butterfly movement path, does not use it's whole available space to move, but it spins around in area equal 4?

seed no. 76520476 - the bottom most in this example

**Comment by feldgendler** [comment]
The butterfly behavior is copied exactly from the original '84 game.

See this detailed spec on the Boulder Dash fan site:
http://www.bd-fans.com/Files/FanStuff/Programming/BDCFF_Objects_Specifications.doc
